name: Continuous 6-Hour Loop

on:
  workflow_dispatch: # Allow manual trigger

jobs:
  continuous-loop-job:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Download the previous artifact (if it exists)
      - name: Download previous artifact
        id: download_artifact
        run: |
          echo "Trying to download the previous artifact..."
          if curl --fail -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -L -o previous_artifact.txt \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts; then
            echo "Previous artifact found."
          else
            echo "No previous artifact found."
            echo "First run or no artifact uploaded."
          fi

      # Step 2: Print the previous artifact content if available
      - name: Print previous artifact content
        run: |
          if [ -f previous_artifact.txt ]; then
            echo "Previous artifact content:"
            cat previous_artifact.txt
          else
            echo "No previous artifact to display."
          fi

      # Step 3: Simulate a 6-hour wait and upload an artifact
      - name: Wait for 6 hours and upload an artifact
        run: |
          echo "Running for 6 hours..."
          sleep $((6 * 60 * 60)) # Sleep for 6 hours
          echo "6 hours passed. Uploading artifact..."
          echo "This artifact was created after 6 hours at $(date)" > artifact_6_hours.txt
        continue-on-error: true

      - name: Upload 6-hour artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact_6_hours
          path: artifact_6_hours.txt

      # Step 4: Trigger the next workflow run before the 6-hour limit
      - name: Trigger the next workflow run
        run: |
          echo "Triggering the next workflow run..."
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/continuous-loop.yml/dispatches \
            -d '{"ref":"main"}'
